export const treatmentArr = [
    {
        name: "Иванова А. К.",
        date: "15.09.2017",
        time: '15:00-16:00',
        type: 'chat1',
        img: "https://www.proza.ru/pics/2017/06/03/1990.jpg",
        diagnostic: "Сахарный диабет",
        comments: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
        price: "112 руб.",
        conclusion: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit",
        conclusionDownload: "Заключение 252525.pdf",
        review: "Lorem ipsum dolor sit amet, consectetuer...",
    }, {
        name: "Иванова А. К.",
        date: "15.09.2017",
        time: '15:00-16:00',
        type: 'chat1',
        img: "https://www.proza.ru/pics/2017/06/03/1990.jpg",
        diagnostic: "Сахарный диабет",
        comments: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
        price: "112 руб.",
        conclusion: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit",
        conclusionDownload: "Заключение 252525.pdf",
        review: "Lorem ipsum dolor sit amet, consectetuer...",
    }, {
        name: "Иванова А. К.",
        date: "15.09.2017",
        time: '15:00-16:00',
        type: 'chat1',
        img: "https://www.proza.ru/pics/2017/06/03/1990.jpg",
        diagnostic: "Сахарный диабет",
        comments: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
        price: "112 руб.",
        conclusion: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit",
        conclusionDownload: "Заключение 252525.pdf",
        review: "Lorem ipsum dolor sit amet, consectetuer...",
    }, {
        name: "Иванова А. К.",
        date: "15.09.2017",
        time: '15:00-16:00',
        type: 'chat1',
        img: "https://www.proza.ru/pics/2017/06/03/1990.jpg",
        diagnostic: "Сахарный диабет",
        comments: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
        price: "112 руб.",
        conclusion: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit",
        conclusionDownload: "Заключение 252525.pdf",
        review: "Lorem ipsum dolor sit amet, consectetuer...",
    },{
        name: "Иванова А. К.",
        date: "15.09.2017",
        time: '15:00-16:00',
        type: 'chat1',
        img: "https://www.proza.ru/pics/2017/06/03/1990.jpg",
        diagnostic: "Сахарный диабет",
        comments: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
        price: "112 руб.",
        conclusion: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit",
        conclusionDownload: "Заключение 252525.pdf",
        review: "Lorem ipsum dolor sit amet, consectetuer...",
    },{
        name: "Иванова А. К.",
        date: "15.09.2017",
        time: '15:00-16:00',
        type: 'chat1',
        img: "https://www.proza.ru/pics/2017/06/03/1990.jpg",
        diagnostic: "Сахарный диабет",
        comments: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
        price: "112 руб.",
        conclusion: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit",
        conclusionDownload: "Заключение 252525.pdf",
        review: "Lorem ipsum dolor sit amet, consectetuer...",
    },{
        name: "Иванова А. К.",
        date: "15.09.2017",
        time: '15:00-16:00',
        type: 'chat1',
        img: "https://www.proza.ru/pics/2017/06/03/1990.jpg",
        diagnostic: "Сахарный диабет",
        comments: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
        price: "112 руб.",
        conclusion: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit",
        conclusionDownload: "Заключение 252525.pdf",
        review: "Lorem ipsum dolor sit amet, consectetuer...",
    },{
        name: "Иванова А. К.",
        date: "15.09.2017",
        time: '15:00-16:00',
        type: 'chat1',
        img: "https://www.proza.ru/pics/2017/06/03/1990.jpg",
        diagnostic: "Сахарный диабет",
        comments: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
        price: "112 руб.",
        conclusion: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit",
        conclusionDownload: "Заключение 252525.pdf",
        review: "Lorem ipsum dolor sit amet, consectetuer...",
    },
];