export const treatmentArr = [
    {
        id: 1,
        id_user: 2223,
        status: "new",
        name: "Иванова А. К.",
        startDate: new Date(2017,9,14,15).getTime()/1000,
        endDate: new Date(2017,9,14,16).getTime()/1000,
        type: 'chat',
        diagnostic: "Сахарный диабет",
        comments: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
        price: "112 руб.",
        conclusion: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit",
        conclusionDownloadName: "Заключение 252525.pdf",
        review: "Lorem ipsum dolor sit amet, consectetuer...",
        rating: 3,
    }, {
        id: 3,
        id_user: 2223,
        status: "new",
        name: "Иванова А. К.",
        startDate: new Date(2017,9,15,15).getTime()/1000,
        endDate: new Date(2017,9,15,16).getTime()/1000,
        type: 'chat',
        diagnostic: "Сахарный диабет",
        comments: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
        price: "112 руб.",
        conclusion: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit",
        conclusionDownloadName: "Заключение 252525.pdf",
        review: "Lorem ipsum dolor sit amet, consectetuer...",
    },
];
/*    {
        name: "Иванова А. К.",
        date: "15.09.2017",
        time: '15:00-16:00',
        type: 'chat1',
        title: 'Отправить сообщение',
        img: "https://www.proza.ru/pics/2017/06/03/1990.jpg",
        diagnostic: "Сахарный диабет",
        comments: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
        price: "112 руб.",
        conclusion: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit",
        conclusionDownload: "Заключение 252525.pdf",
        review: "Lorem ipsum dolor sit amet, consectetuer...",

        btnText: "Прикрепленный файл с длинным предлинным названием.doc",
    }, {
        name: "Иванова А. К.",
        date: "15.09.2017",
        time: '15:00-16:00',
        type: 'telephone',
        title: 'Звонок',
        img: "https://www.proza.ru/pics/2017/06/03/1990.jpg",
        diagnostic: "Сахарный диабет",
        comments: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
        price: "112 руб.",
        conclusion: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit",
        conclusionDownload: "Заключение 252525.pdf",
        review: "Lorem ipsum dolor sit amet, consectetuer...",
        btnText: "Прикрепленный файл с длинным предлинным названием.doc",
    }, {
        name: "Иванова А. К.",
        date: "15.09.2017",
        time: '15:00-16:00',
        type: 'chat1',
        img: "https://www.proza.ru/pics/2017/06/03/1990.jpg",
        diagnostic: "Сахарный диабет",
        comments: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
        price: "112 руб.",
        conclusion: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit",
        conclusionDownload: "Заключение 252525.pdf",
        review: "Lorem ipsum dolor sit amet, consectetuer...",
        btnText: "Прикрепленный файл с длинным предлинным названием.doc",
    }, {
        name: "Иванова А. К.",
        date: "15.09.2017",
        time: '15:00-16:00',
        type: 'chat1',
        img: "https://www.proza.ru/pics/2017/06/03/1990.jpg",
        diagnostic: "Сахарный диабет",
        comments: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
        price: "112 руб.",
        conclusion: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit",
        conclusionDownload: "Заключение 252525.pdf",
        review: "Lorem ipsum dolor sit amet, consectetuer...",
        btnText: "Прикрепленный файл с длинным предлинным названием.doc",
    },{
        name: "Иванова А. К.",
        date: "15.09.2017",
        time: '15:00-16:00',
        type: 'chat1',
        img: "https://www.proza.ru/pics/2017/06/03/1990.jpg",
        diagnostic: "Сахарный диабет",
        comments: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
        price: "112 руб.",
        conclusion: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit",
        conclusionDownload: "Заключение 252525.pdf",
        review: "Lorem ipsum dolor sit amet, consectetuer...",
        btnText: "Прикрепленный файл с длинным предлинным названием.doc",
    },{
        name: "Иванова А. К.",
        date: "15.09.2017",
        time: '15:00-16:00',
        type: 'chat1',
        img: "https://www.proza.ru/pics/2017/06/03/1990.jpg",
        diagnostic: "Сахарный диабет",
        comments: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
        price: "112 руб.",
        conclusion: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit",
        conclusionDownload: "Заключение 252525.pdf",
        review: "Lorem ipsum dolor sit amet, consectetuer...",
        btnText: "Прикрепленный файл с длинным предлинным названием.doc",
    },{
        name: "Иванова А. К.",
        date: "15.09.2017",
        time: '15:00-16:00',
        type: 'chat1',
        img: "https://www.proza.ru/pics/2017/06/03/1990.jpg",
        diagnostic: "Сахарный диабет",
        comments: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
        price: "112 руб.",
        conclusion: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit",
        conclusionDownload: "Заключение 252525.pdf",
        review: "Lorem ipsum dolor sit amet, consectetuer...",
        btnText: "Прикрепленный файл с длинным предлинным названием.doc",
    },
];

export const filesArr = [
    {
        btnText: "Файл.doc",
    },{
        btnText: "Прикрепленный файл с длинным предлинным названием.doc",
    },{
        btnText: "52525.pdf",
    },{
        btnText: "Прикрепленный файл с длинным предлинным названием.doc",
    },{
        btnText: "52525.pdf",
    },
];

