const minute = 60 * 1000;
const hour = minute * 60;
const day = hour * 24;
const now = Date.now();

export const historyArr = [
    {
        id: 1,
        status: "new",
        name: "Иванова А. К.",
        startDate: new Date(2017,9,14,15).getTime(),
        endDate: new Date(2017,9,14,16).getTime(),
        type: 'chat1',
        title:'Чат',
        diagnostic: "Сахарный диабет",
        comments: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
        price: "112 руб.",
        conclusion: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit",
        conclusionDownload: "Заключение 252525.pdf",
        review: "Lorem ipsum dolor sit amet, consectetuer...",
    }, {
        id: 3,
        status: "new",
        name: "Иванова А. К.",
        startDate: new Date(2017,9,15,15).getTime(),
        endDate: new Date(2017,9,15,16).getTime(),
        type: 'chat1',
        title:'Чат',
        diagnostic: "Сахарный диабет",
        comments: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
        price: "112 руб.",
        conclusion: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit",
        conclusionDownload: "Заключение 252525.pdf",
        review: "Lorem ipsum dolor sit amet, consectetuer...",
    }, {
        id: 5,
        status: "new",
        name: "Иванова А. К.",
        startDate: new Date(2017,9,17,15).getTime(),
        endDate: new Date(2017,9,17,16).getTime(),
        type: 'chat1',
        title:'Чат',
        diagnostic: "Сахарный диабет",
        comments: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
        price: "112 руб.",
        conclusion: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit",
        conclusionDownload: "Заключение 252525.pdf",
        review: "Lorem ipsum dolor sit amet, consectetuer...",
    }, {
        id: 8,
        status: "new",
        name: "Иванова А. К.",
        startDate: new Date(2017,9,21,14,30).getTime(),
        endDate: new Date(2017,9,21,15).getTime(),
        type: 'chat1',
        title:'Чат',
        diagnostic: "Сахарный диабет",
        comments: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
        price: "112 руб.",
        conclusion: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit",
        conclusionDownload: "Заключение 252525.pdf",
        review: "Lorem ipsum dolor sit amet, consectetuer...",
    },{
        id: 11,
        status: "new",
        name: "Иванова А. К.",
        startDate: new Date(2017,9,27,15,20).getTime(),
        endDate: new Date(2017,9,27,15,40).getTime(),
        type: 'chat1',
        title:'Чат',
        diagnostic: "Сахарный диабет",
        comments: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
        price: "112 руб.",
        conclusion: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit",
        conclusionDownload: "Заключение 252525.pdf",
        review: "Lorem ipsum dolor sit amet, consectetuer...",
    },{
        id: 15,
        status: "topical",
        name: "Иванова А. К.",
        startDate: new Date(2017,10,14,15,30).getTime(),
        endDate: new Date(2017,10,14,16).getTime(),
        type: 'chat1',
        title:'Чат',
        diagnostic: "Сахарный диабет",
        comments: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
        price: "112 руб.",
        conclusion: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit",
        conclusionDownload: "Заключение 252525.pdf",
        review: "Lorem ipsum dolor sit amet, consectetuer...",
    },{
        id: 18,
        status: "extra",
        name: "Иванова А. К.",
        startDate: new Date(2017,10,14,15).getTime(),
        endDate: new Date(2017,10,14,16).getTime(),
        type: 'chat1',
        title:'Чат',
        diagnostic: "Сахарный диабет",
        comments: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
        price: "112 руб.",
        conclusion: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit",
        conclusionDownload: "Заключение 252525.pdf",
        review: "Lorem ipsum dolor sit amet, consectetuer...",
    },{
        id: 19,
        status: "completed",
        name: "Иванова А. К.",
        startDate: new Date(2017,10,15,15,50).getTime(),
        endDate: new Date(2017,10,15,16).getTime(),
        type: 'chat1',
        title:'Чат',
        diagnostic: "Сахарный диабет",
        comments: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
        price: "112 руб.",
        conclusion: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit",
        conclusionDownload: "Заключение 252525.pdf",
        review: "Lorem ipsum dolor sit amet, consectetuer...",
    },
    {
        id: 199,
        status: "completed",
        name: "Иванова А. К.",
        startDate: new Date(2018,5,15,15,50).getTime(),
        endDate: new Date(2018,5,15,16).getTime(),
        type: 'chat1',
        title:'Чат',
        diagnostic: "Сахарный диабет",
        comments: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
        price: "112 руб.",
        conclusion: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit",
        conclusionDownload: "Заключение 252525.pdf",
        review: "Lorem ipsum dolor sit amet, consectetuer...",
    },
];